# Generated by Django 3.1.7 on 2021-04-29 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='redsocialartista',
            name='imagen_rs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Redsocial_imagen_rs', to='myapi.redsocial'),
        ),
        migrations.AlterField(
            model_name='redsocial',
            name='imagen_rs',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='redsocialartista',
            name='id_rs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Redsocial_id_rs', to='myapi.redsocial'),
        ),
    ]
