# Generated by Django 3.1.7 on 2021-04-29 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_auto_20210429_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='redsocial',
            name='id_a',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapi.artista'),
        ),
        migrations.AddField(
            model_name='redsocial',
            name='url_rs',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.DeleteModel(
            name='RedsocialArtista',
        ),
    ]
