# Generated by Django 3.1.7 on 2021-04-29 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_auto_20210429_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redsocial',
            name='imagen_rs',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
