# Generated by Django 3.1.7 on 2021-05-03 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_auto_20210429_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datapp',
            name='nombreapp',
        ),
        migrations.AddField(
            model_name='datapp',
            name='mensajeapp',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
    ]
