# Generated by Django 3.1.7 on 2021-05-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_auto_20210503_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapp',
            name='titulomapp',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
