# Generated by Django 3.1.7 on 2021-07-23 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0008_datapp_iconapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id_c', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_c', models.CharField(max_length=100)),
                ('imagen_c', models.ImageField(blank=True, null=True, upload_to='')),
                ('url_c', models.CharField(max_length=200, null=True)),
                ('id_a', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapi.artista')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id_tag', models.BigAutoField(primary_key=True, serialize=False)),
                ('imagen_tag', models.ImageField(blank=True, null=True, upload_to='')),
                ('genero_tag', models.CharField(max_length=100)),
                ('idioma_tag', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Wallpaper',
        ),
        migrations.AddField(
            model_name='cancion',
            name='id_tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapi.tag'),
        ),
        migrations.AddField(
            model_name='artista',
            name='id_tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapi.tag'),
        ),
    ]
