# Generated by Django 3.1.7 on 2022-10-12 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0009_auto_20210722_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redsocial',
            name='imagen_rs',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
