# Generated by Django 3.1.7 on 2022-10-19 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0010_auto_20221011_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id_v', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_v', models.CharField(max_length=100)),
                ('imagen_v', models.ImageField(blank=True, null=True, upload_to='')),
                ('url_v', models.CharField(max_length=200, null=True)),
                ('id_a', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapi.artista')),
                ('id_tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapi.tag')),
            ],
        ),
        migrations.DeleteModel(
            name='Cancion',
        ),
    ]
